controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute
api_login_check:
  path: /api/login_check
localite_routes:
  resource: "../src/Controller/LocaliteController.php"
  type: annotation
app_get_data:
  path: /api/entreprise
  controller: App\Controller\EntrepriseController::getData
  methods: GET

app_create_data:
  path: /api/entreprise
  controller: App\Controller\EntrepriseController::createData
  methods: POST

app_update_data:
  path: /api/entreprise/{id}
  controller: App\Controller\EntrepriseController::updateData
  methods: [PATCH]

app_delete_data:
  path: /api/entreprise/{id}
  controller: App\Controller\EntrepriseController::deleteData
  methods: [DELETE]

app_get_data_localite:
  path: /localite
  controller: App\Controller\LocaliteController::getLocalites
  methods: GET

app_create_data_localite:
  path: /localite
  controller: App\Controller\LocaliteController::createLocalite
  methods: POST

app_update_data_localite:
  path: /localite/{id}
  controller: App\Controller\LocaliteController::updateLocalite
  methods: [PATCH]

app_delete_data_localite:
  path: /localite/{id}
  controller: App\Controller\LocaliteController::deleteLocalite
  methods: [DELETE]

app_getdata_offrestage:
  path: /offrestage
  controller: App\Controller\OffreStageContollerController::getOffreStage
  methods: GET

app_create_offrestage:
  path: /offrestage
  controller: App\Controller\OffreStageContollerController::createOffreStage
  methods: POST

app_update_data_offrestage:
  path: /offrestage/{id}
  controller: App\Controller\OffreStageController::updateOffreStage
  methods: [PATCH]

app_delete_data_offrestage:
  path: /offrestage/{id}
  controller: App\Controller\OffreStageController::deleteOffreStage
  methods: [DELETE]

app_get_data_competence:
  path: /competence
  controller: App\Controller\CompetenceController::getCompetence
  methods: GET

app_create_data_competence:
  path: /competence
  controller: App\Controller\CompetenceController::createCompetence
  methods: POST

app_update_data_competence:
  path: /competence/{id}
  controller: App\Controller\CompetenceController::updateCompetence
  methods: [PATCH]

app_delete_data_competence:
  path: /competence/{id}
  controller: App\Controller\CompetenceController::deleteCompetence
  methods: [DELETE]

app_get_data_promotion:
  path: /promotion
  controller: App\Controller\PromotionController::getPromotion
  methods: GET

app_create_data_promotion:
  path: /promotion
  controller: App\Controller\PromotionController::createPromotion
  methods: POST

app_update_data_promotion:
  path: /promotion/{id}
  controller: App\Controller\PromotionController::updatePromotion
  methods: [PATCH]

app_delete_data_promotion:
  path: /promotion/{id}
  controller: App\Controller\PromotionController::deletePromotion
  methods: [DELETE]

api_application_index:
    path: '/api/application/user/{userId}'
    controller: 'App\Controller\ApplicationController::index'
    methods: ['GET']

api_application_create:
  path: /api/application/create
  controller: App\Controller\ApplicationController::create
  methods: POST

api_application_update:
  path: /api/application/update/{id}
  controller: App\Controller\ApplicationController::update
  methods: PATCH

api_application_delete:
  path: /api/application/delete/{id}
  controller: App\Controller\ApplicationController::delete
  methods: DELETE
  
api_application_all:
    path: '/api/application/all'
    controller: 'App\Controller\ApplicationController::all'
    methods: ['GET']